id: P000469
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:41:32.959586
source_metadata:
  id: bdr:W1CZ164
  title: ཀུན་ཁྱབ་རྡོ་རྗེ་དྲག་པོ་རྩལ་གྱི་སྤྱན་འདྲེན་བསྐང་བ་ཕྲིན་བཅོལ་དང་བཅས་པ
  author: ''
  volumes:
    9df6d9601f2345ed93cf7ec090d7af70:
      image_group_id: I1CZ677
      title: Volume 1 of kun khyab rdo rje drag po rtsal gyi spyan 'dren bskang ba
        phrin bcol dang bcas pa
      volume_number: 1
      total_pages: 34
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
